### ISSUE TITLE
Running the code on MATLAB R2019b

### ISSUE THREAD

**Issue by mdrpanwar** [phillipi/crisp-boundaries#2]
Hi Phillip!
I have been trying to execute _crisp-boundaries_ on R2019b and have been facing problems:
1. It does not compile and here's what I get:
![kde](https://user-images.githubusercontent.com/39766613/67152479-da4e0900-f2f4-11e9-9ce7-0032b54f127b.png)
Since this doesn't actually tell me what's wrong with `makemex_kde.m` and I was able to run the code without compiling on R2015b, I thought of trying to proceed anyway:

`E = findBoundaries(I);` resulted in deprecation errors since some of the used functions have changed over recent MATLAB versions. I replaced names until it made sense and then I got to:

![cb](https://user-images.githubusercontent.com/39766613/67152517-8ee82a80-f2f5-11e9-85bf-0cdb2ea00006.png)

I have no idea how to proceed further. Any help is appreciated. 
Also, could you tell me the MATLAB version this code was originally written in? Also, will there be a recent MATLAB version of the code?

Thanks!

**Comment by phillipi** [comment]
I think the code was working at least up to MATLAB R2014b (I wrote it in 2014). It may take quite some work to update it for 2019.

**Comment by mdrpanwar** [comment]
Thanks for the reply. I just thought to ask you if the error makes sense and if there was some quick fix. It seems that translation to R2019b would require understanding the whole code since a lot has changed in MATLAB since 2014. I was just having second thoughts if that is worth trying given that I am a beginner in MATLAB and code anyway works brilliantly on older MATLAB versions. Let me know if you have a say in that. You may close the issue otherwise. Thanks.

**Comment by phillipi** [comment]
It looks like the error is in the random forest code. You actually don't need the random forest, it just makes things faster. You can turn it off using `opts.approximate_PMI=false`.

**Comment by AutoFine** [comment]
Hi, Phillipi 

Thanks for sharing your scripts. I commented on this post because I have same problem for MATLAB R2018b. And, I made the change as you suggested, opts.approximate_PMI=false, in the setEnvironment.m file. But, after restarting matlab, I still have same problem as below: 
" Error using compile (line 51)
Something went wrong with compilation of the kde toolbox.
Try editing ./Code/Toolboxes/@kde/mex/makemex_kde.m
See http://www.ics.uci.edu/~ihler/code/kde.html for more documentation on how to install this toolbox. "
 Did make the change opts.approximate_PMI=false in wrong file? If not, can you please suggest how can I continue without using the random forest? I would like to detect and extract contour only. Thank you very much. 

Best regards
